services:
  nginx-server:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Landing-Page-Static:/usr/share/nginx/html/projects/static-landing
      - ./Landing-Page-Responsive:/usr/share/nginx/html/projects/adaptive-landing
      - ./Paired-Colors:/usr/share/nginx/html/projects/colors-game
    depends_on:
      - server
  server:
    image: node:alpine
    # depends_on:
    #   - mysql
    expose:
      - '5173'
    environment:
      MYSQL_DATABASE: study_db
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
    volumes:
      - .:/app
    command: [sh, -c, 'cd /app/Core && npm run dev']
  # mysql:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: aezakmi
  #     MYSQL_DATABASE: study_db
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  # adminer:
  #   image: adminer
  #   depends_on:
  #     - mysql
  #   ports:
  #     - '8080:8080'

volumes:
  mysql_data:
