services:
  nginx-server:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Landing-Page-Static:/usr/share/nginx/html/projects/static-landing
      - ./Landing-Page-Responsive:/usr/share/nginx/html/projects/adaptive-landing
      - ./Paired-Colors:/usr/share/nginx/html/projects/colors-game
      - ./Leetcode-Parser:/usr/share/nginx/html/projects/leetcode
    depends_on:
      - frontend
  frontend:
    image: node:alpine
    expose:
      - ${FRONTEND_PORT}
    volumes:
      - .:/app
    command: [sh, -c, 'cd /app/Core && npm run dev']
    env_file:
      - '.env'
    # depends_on:
    #   - mysql
  # mysql:
  #   image: mysql
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  # adminer:
  #   image: adminer
  #   depends_on:
  #     - mysql
  #   ports:
  #     - '8080:8080'

volumes:
  mysql_data:
