version: '3'

services:
  server:
    image: node:alpine
    ports:
      - '5173:5173'
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: study_db
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
    volumes:
      - ../:/app
    command: [sh, -c, 'cd ./app/Core && npm run update && npm run dev']
  mysql:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: aezakmi
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - '5200:5200'

volumes:
  mysql_data:
