# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy on GitHub Pages

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  buildCore:
    strategy:
      matrix:
        node-version: [latest]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./app
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Cache next step
      id: installCore
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: key-${{ hashFiles('**/Core/package-lock.json') }}
        
    - name: Install npm
      if: steps.installCore.outputs.cache-hit != 'true'
      run: npm ci
      
    - name: Build Core
      run: npm run build
