# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy on GitHub Pages

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  buildCore:
    strategy:
      matrix:
        node-version: [latest]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./Core
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Core/package-lock.json'
        registry-url: https://npm.pkg.github.com/
      
    - name: Cache next step
      id: installCore
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: key-${{ hashFiles('**/Core/package-lock.json') }}
        
    - name: Install npm
      if: steps.installCore.outputs.cache-hit != 'true'
      run: npm ci
      env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_READ_PACKAGE }}
      
    - name: Build Core
      run: npm run build

    - name: Save Artifacts
      uses: actions/upload-artifacts@v4
      with:
        name: Core
        path: Core/dist
  deploy:
    needs: buildCore
    strategy:
      matrix:
        node-version: [latest]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Upload to GitHub Pages
      uses: actions/download-artifact@v4
      with:
        name: Core
