# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BUild and deploy on GitHub Pages

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  buildCore:
    strategy:
      matrix:
        node-version: [latest]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Go to Core
      run: cd Core
    - name: Install npm
      run: npm ci
    - name: Build Core
      run: npm run build
